const mongoose = require('mongoose');

const {Schema} = mongoose;
var ObjectId = require('mongodb').ObjectID;

//Comment : id auto generated by mongoDB
const commentSchema  = new Schema({
  userId: { 
    type: ObjectId, 
    required: true 
  },
  articleId: { 
    type: ObjectId, 
    required: true 
  },
  body: { 
    type: String, 
    required: true 
  },
  date: { 
    type: Date, 
    default: Date.now 
  },
  likes: { 
    type: Number, 
    default: 0, 
    min: 0 
  }
});
const Comment = mongoose.model('Comment', commentSchema);



module.exports = Comment;